package com.ninjacart.featureExtraction.other.CreditReportResponseModel;

public enum ReportType {
    INSIGHTS_REPORT, ADDRESS_REPORT, SMS_REPORT, BANK_STATEMENT, RAW_BANK_STATEMENT_REPORT, ANALYZED_JSON_BANK_STATEMENT_REPORT, ANALYZED_EXCEL_BANK_STATEMENT_REPORT, MCA_REPORT, EPF_REPORT, GST_REPORT, RELATED_PARTIES_INSIGHTS_REPORT,KARZA_FIR_INSIGHTS_REPORT, CRIF_REPORT, CRIF_QUESTIONNAIRE
}